function MyObject(id, key1, key2, key3, key4) {
    this.id = id;
    this.key1 = key1;
    this.key2 = key2;
    this.key3 = key3;
    this.key4 = key4;
}
var arr = [
    new MyObject(1, "Apple", 100, true, [1, 2]),
    new MyObject(2, "Nike", 1500, false, ["Black", "White"]),
    new MyObject(3, "Laptop", 80000, true, { ram: "8GB" }),
    new MyObject(4, "Book", 300, true, { author: "Ali" }),
    new MyObject(5, "Car", 2000000, false, { model: "2020" }),
    new MyObject(6, "User", 1, true, ["Admin", "Editor"]),
    new MyObject(7, "Pakistan", 75, true, ["Karachi", "Lahore"]),
    new MyObject(8, "Age", 25, true, "Male"),
    new MyObject(9, "Language", "JS", false, "Advanced"),
    new MyObject(10, "Fruit", "Mango", true, "Seasonal"),
    new MyObject(11, "Phone", "iPhone", true, { version: 17 }),
    new MyObject(12, "Laptop", "Dell", true, { ssd: "512GB" }),
    new MyObject(13, "Shirt", "Medium", true, ["M", "L"]),
    new MyObject(14, "Subject", "Math", true, 88),
    new MyObject(15, "Student", "Sara", true, { roll: 45 }),
    new MyObject(16, "Color", "Red", true, "#FF0000"),
    new MyObject(17, "Temp", 36, true, "Celsius"),
    new MyObject(18, "Pet", "Cat", false, "Vaccinated"),
    new MyObject(19, "Movie", "Inception", true, 9.0),
    new MyObject(20, "Job", "Developer", true, "Remote"),
    new MyObject(21, "Browser", "Chrome", true, 115),
    new MyObject(22, "Framework", "React", true, "Frontend"),
    new MyObject(23, "Snack", "Chips", true, "Spicy"),
    new MyObject(24, "City", "Islamabad", true, 540),
    new MyObject(25, "Singer", "Atif", true, 5),
    new MyObject(26, "Brand", "Samsung", true, ["S20", "A52"]),
    new MyObject(27, "Student", "Ali", true, "A Grade"),
    new MyObject(28, "Language", "Urdu", true, "Native"),
    new MyObject(29, "Tool", "Hammer", true, "2kg"),
    new MyObject(30, "Building", "Mall", true, 5),
    new MyObject(31, "TV", "Sony", true, "55 inch"),
    new MyObject(32, "Drink", "Tea", true, "Hot"),
    new MyObject(33, "Car", "Honda", true, "White"),
    new MyObject(34, "Country", "India", true, "IN"),
    new MyObject(35, "File", "Resume.pdf", true, "1MB"),
    new MyObject(36, "Theme", "Dark", false, "Disabled"),
    new MyObject(37, "Dish", "Biryani", true, "Spicy"),
    new MyObject(38, "Member", "Wiki", true, "Admin"),
    new MyObject(39, "Ticket", "VIP", true, 3000),
    new MyObject(40, "Exam", "AI", true, "2025-08-01"),
    new MyObject(41, "Podcast", "TechTalk", true, "30min"),
    new MyObject(42, "Project", "Chatbot", false, "Ongoing"),
    new MyObject(43, "Event", "Hackathon", true, 50),
    new MyObject(44, "Code", "XYZ123", true, "Valid"),
    new MyObject(45, "Animal", "Dog", true, "Labrador"),
    new MyObject(46, "Food", "Pizza", true, ["Cheese", "Olives"]),
    new MyObject(47, "Day", "Monday", false, "Working"),
    new MyObject(48, "Currency", "PKR", true, "₨"),
    new MyObject(49, "Weather", "Rainy", true, "Humid"),
    new MyObject(50, "Account", "Savings", true, 5000),
];

console.log(arr[1]);
